### PR TITLE
Added toJpeg function

### PR DESCRIPTION
**Pull request by StefanoGitHub**
@tsayen ,
I needed to save file as .jpeg, so I though it might be useful for somebody else.
Thanks for this useful library, it saved me a lot of headaches!

### CODE REVIEW

**Comment by tsayen** [comment]
Hi, thanks for contributing! I suggest we add "quality" to rendering options (instead of introducing a function parameter), and take it into account also when rendering to PNG.

**Comment by StefanoGitHub** [comment]
Well we can put `quality` inside the `options`, it will only be used for jpeg images, default to 100%.
Would that work for you?

**Comment by tsayen** [comment]
Yes, that would be great

**Comment by StefanoGitHub** [comment]
done! ;)

**Comment by StefanoGitHub** [comment]
I also tried to improve a little the docs, please have a look at the `README.md` file, just in case I wrote something wrong

**Comment by StefanoGitHub** [comment]
@tsayen 
sorry I forgot to correct the example in the doc after changing the code as you suggested; it should be:
```javascript
domtoimage.toJpeg(document.getElementById('my-node'), { quality: 0.95 })
    .then(function (dataUrl) {
        var link = document.createElement('a');
        link.download = 'my-image-name.jpeg';
        link.href = dataUrl;
        link.click();
    });
```
(note the `quality` attribute in the options object)

**Comment by tsayen** [comment]
That's all corrected, no worries. Thanks for contributing once again!

**Pull request merged**
