### PR TITLE
DOM-objects without an `style`-attribute can now be rendered

### LINKED ISSUE #182: Katex (MathML-Library) creates the error "target is undefined"
Hi,

I'm using [Katex](https://github.com/Khan/KaTeX) to display mathematical expressions and I wan't to save them as images, but dom-to-image crashes with the error "target is undefined".
I found out that it's happening in this [function](https://github.com/tsayen/dom-to-image/blob/master/src/dom-to-image.js#L230):
```js
function cloneStyle() {
    copyStyle(window.getComputedStyle(original), clone.style);

    function copyStyle(source, target) {
        if (source.cssText) target.cssText = source.cssText;
        else copyProperties(source, target);

        function copyProperties(source, target) {
            util.asArray(source).forEach(function (name) {
                target.setProperty(
                    name,
                    source.getPropertyValue(name),
                    source.getPropertyPriority(name)
                );
            });
        }
    }
}
```
Basically `clone` is a `<mi />` Element from [MathML](https://developer.mozilla.org/en-US/docs/Web/MathML) which doesn't have a `style`-attribute, therefore the `target.setProperties()`-function is executed on an undefined attribute and crashes.

Here is a [simple demo project](https://github.com/tsayen/dom-to-image/files/1678812/bug.report.zip). Run `npm install`, `npm run start` to start it.

### PR DESCRIPTION
**Pull request by Syndesi**
This resolves #182 . Btw, your current tests are sometimes failing, but this new commit doesn't add any new failures :)

### CODE REVIEW

**Comment by pacproduct** [comment]
@Syndesi : Made a very similar PullRequest that includes a bit more safeguarding. Can't be sure all of them are necessary...

See https://github.com/tsayen/dom-to-image/pull/246

**Comment by Syndesi** [comment]
@pacproduct Sry for the late reply, but I moved and had no internet until know. Your pull request is indeed better than my solution and therefore I'll close this one. Maybe @tsayen can merge it in time :)

**Comment by tsayen** [comment]
Hi, thanks for contributing! 
Indeed, you're right about the tests. They fail on my local machine as well, that one with the text node. Well, I can sort it out later.
Your solution looks fine to me, as it doesn't introduce new regression test failures, although it would be nice to add a test for that particular case. Anyway, if you reopen this request, I can merge it.

**Comment by ProfessorX737** [comment]
Please merge this change into master. I cannot render image with math without it

**Comment by michaeljelly** [comment]
@tsayen any chance this can be merged now?

**Comment by Syndesi** [comment]
Permanently closed as there is no activity by the repository owner anymore.

**Pull request closed without merging**
